alter table TIREFITTING_REQUEST add constraint FK_TIREFITTING_REQUEST_ON_SERVICEPOINT foreign key (SERVICEPOINT) references TIREFITTING_SERVICE_POINT(ID);
create index IDX_TIREFITTING_REQUEST_ON_SERVICEPOINT on TIREFITTING_REQUEST (SERVICEPOINT);
